export const size = {
  huge: 50,
  xxxtitle: 38,
  xxtitle: 36,
  xtitle: 34,
  title: 32,
  h1: 30,
  h2: 28,
  h3: 26,
  h4: 25,
  h5: 24,
  h6: 22,
  xxlarge: 20,
  xlarge: 19,
  large: 18,
  medium: 17,
  normal: 16,
  small: 15,
  xsmall: 14,
  xxsmall: 13,
  tiny: 12,
  xtiny: 11,
  xxtiny: 10,
  xxxtiny: 9,
};

export const family = {
  SP_Regular: 'SofiaProRegular',
  SP_Medium: 'SofiaProMedium',
  SP_BlackItalic: 'SofiaProBlack-Italic',
  SP_SemiBold: 'SofiaProSemiBold',
  SP_SemiBold_Italic: 'SofiaProSemiBold-Italic',
  SP_Bold: 'SofiaProBold',
};